language: r
r:
 - 3.5.2
cache: packages
sudo: false
warnings_are_errors: true
r_check_args: --as-cran

git:
  depth: 5

r_packages:
 - devtools
 - covr
 - roxygen2
 - testthat
 - rmarkdown
 - knitr
 - magrittr
 - tibble
 - dplyr
 - ggplot2
 - RColorBrewer
 - data.table
 - rootSolve
 - utils
 - rprojroot
 - R.utils
 - Hmisc
 - readr
 - zFactor

bioc_packages:
  - S4Vectors
  - rhdf5

before_script:
 - R -e "devtools::document()"

after_success:
  - Rscript -e "covr::codecov()"
